from __future__ import annotations

import json
import re
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any
from urllib.parse import unquote, urlparse

from videocp.app import DownloadOptions, download_jobs
from videocp.browser import BrowserConfig, open_download_browser_session
from videocp.config import AppConfig, WatermarkConfig, load_app_config
from videocp.mac_scheduler import ensure_app_config, resolve_config_path
from videocp.profile import default_profile_dir, detect_system_browser_executable
from videocp.profile_expander import expand_profile
from videocp.publisher import PublishResult, check_tencent_login_status, is_login_state_publish_error, publish_to_channel
from videocp.runtime_log import log_warn
from videocp.sync_history import SyncHistoryEntry, add_entry, find_processed_entry, load_history
from videocp.ytdlp import YtdlpPlaylistResult, expand_ytdlp_playlist


VIDEO_SUFFIXES = {".mp4", ".m4v", ".mov", ".webm", ".mkv"}
TAG_OR_MENTION_RE = re.compile(r"[#@][^\s#@]+")
DEFAULT_YOUTUBE_EXTRACTOR_ARGS = "youtube:player_client=mweb;fetch_pot=always"


@dataclass(slots=True)
class WorkflowResult:
    ok: bool
    action: str
    path: str = ""
    content_id: str = ""
    title: str = ""
    feed_id: str = ""
    share_url: str = ""
    error: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(slots=True)
class ProfileParseResult:
    ok: bool
    url: str
    name: str = ""
    first_video_url: str = ""
    error: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _as_bool(value: Any, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def _split_inputs(value: str) -> list[str]:
    items: list[str] = []
    for line in str(value or "").splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            items.append(stripped)
    return items


def _app_support_dir() -> Path:
    path = Path.home() / "Library" / "Application Support" / "Videocp Studio"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _write_youtube_cookie_text(cookie_text: str) -> Path | None:
    text = str(cookie_text or "").strip()
    if not text:
        return None
    if "# Netscape HTTP Cookie File" not in text.splitlines()[:3]:
        text = "# Netscape HTTP Cookie File\n# Generated by Videocp Studio\n\n" + text
    cookie_path = _app_support_dir() / "youtube-cookies.txt"
    cookie_path.write_text(text.rstrip() + "\n", encoding="utf-8")
    cookie_path.chmod(0o600)
    return cookie_path


def _resolve_optional_path(value: Any, base_dir: Path) -> Path | None:
    raw = str(value or "").strip()
    if not raw:
        return None
    return resolve_config_path(raw, base_dir)


def _default_ytdlp_extractor_args(value: str) -> str:
    current = str(value or "").strip()
    return current or DEFAULT_YOUTUBE_EXTRACTOR_ARGS


def _workflow_app_config(base_dir: Path, download_dir: Path) -> AppConfig:
    loaded = load_app_config(None, start_dir=base_dir)
    return AppConfig(
        output_dir=download_dir,
        profile_dir=loaded.profile_dir or default_profile_dir(),
        browser_path=loaded.browser_path,
        headless=loaded.headless,
        timeout_secs=loaded.timeout_secs,
        max_concurrent=loaded.max_concurrent,
        max_concurrent_per_site=loaded.max_concurrent_per_site,
        start_interval_secs=loaded.start_interval_secs,
        watermark=loaded.watermark if loaded.watermark else WatermarkConfig(),
        profile_videos_count=loaded.profile_videos_count,
        bilibili_download_mode=loaded.bilibili_download_mode,
        source_path=loaded.source_path,
    )


def run_download_from_app_config(app_config_path: Path, *, force_redownload: bool = False) -> list[dict[str, Any]]:
    app_config = ensure_app_config(app_config_path)
    base_dir = app_config_path.parent
    download_raw = app_config.get("download") or {}
    inputs = _split_inputs(str(download_raw.get("inputs_text", "")))
    output_dir_raw = str(download_raw.get("output_dir") or "").strip()
    history_file = resolve_config_path(download_raw.get("history_file", "./download_history_mac.json"), base_dir)
    count = max(1, int(download_raw.get("count") or 1))
    order = str(download_raw.get("order") or "latest").strip().lower()
    youtube_auto_token = _as_bool(download_raw.get("youtube_auto_token"), False)
    ytdlp_extractor_args = _default_ytdlp_extractor_args(str(download_raw.get("ytdlp_extractor_args") or ""))
    ytdlp_cookies_file = _write_youtube_cookie_text(str(download_raw.get("youtube_cookies_text") or ""))
    if ytdlp_cookies_file is None:
        ytdlp_cookies_file = _resolve_optional_path(download_raw.get("youtube_cookies_path"), base_dir)
    ytdlp_remote_components = _as_bool(download_raw.get("ytdlp_remote_components"), True)
    if youtube_auto_token:
        return [
            WorkflowResult(
                ok=False,
                action="failed",
                error="旧版 YouTube 自动 Token 插件会反复打开 Chrome，已禁用。请关闭该开关后重试，或在高级参数中手动填写已确认可用的 yt-dlp 参数。",
            ).to_dict()
        ]
    if order not in {"latest", "popular"}:
        order = "latest"

    if not inputs:
        return [WorkflowResult(ok=False, action="failed", error="请先填写下载链接或主页链接").to_dict()]
    if not output_dir_raw:
        return [WorkflowResult(ok=False, action="failed", error="请先选择视频保存位置").to_dict()]

    output_dir = resolve_config_path(output_dir_raw, base_dir)
    app_cfg = _workflow_app_config(base_dir, output_dir)
    bilibili_download_mode = str(download_raw.get("bilibili_download_mode") or app_cfg.bilibili_download_mode or "tv").strip().lower()
    if bilibili_download_mode not in {"tv", "web", "ytdlp"}:
        bilibili_download_mode = "tv"
    history = load_history(history_file)
    publish_history_file = resolve_config_path(
        (app_config.get("publish") or {}).get("history_file", "./publish_history_mac.json"),
        base_dir,
    )
    publish_history = load_history(publish_history_file)
    processed_content_ids: set[str] = set()
    if not force_redownload:
        processed_content_ids = {
            entry.content_id
            for entry in history.entries
            if entry.task_name == "directory_download" and entry.status == "ok"
        }
        processed_content_ids.update(
            entry.content_id
            for entry in publish_history.entries
            if entry.task_name == "directory_publish" and entry.status == "ok"
        )
    results = download_jobs(
        DownloadOptions(
            raw_inputs=inputs,
            input_file=None,
            output_dir=app_cfg.output_dir,
            profile_dir=app_cfg.profile_dir,
            browser_path=app_cfg.browser_path,
            headless=app_cfg.headless,
            timeout_secs=app_cfg.timeout_secs,
            max_concurrent=app_cfg.max_concurrent,
            max_concurrent_per_site=app_cfg.max_concurrent_per_site,
            start_interval_secs=app_cfg.start_interval_secs,
            watermark=app_cfg.watermark,
            profile_videos_count=count,
            profile_order=order,
            bilibili_download_mode=bilibili_download_mode,
            ytdlp_extractor_args=ytdlp_extractor_args,
            ytdlp_cookies_file=ytdlp_cookies_file,
            ytdlp_remote_components=ytdlp_remote_components,
            skip_content_ids=processed_content_ids,
            force_redownload=force_redownload,
        )
    )
    payload: list[dict[str, Any]] = []
    for item in results:
        meta = item.extraction.metadata if item.extraction else None
        reused = bool(item.ok and item.artifact and item.artifact.attempts and item.artifact.attempts[0].get("mode") == "reuse")
        if item.ok and meta and meta.content_id and find_processed_entry(history, "directory_download", meta.content_id) is None:
            add_entry(
                history,
                SyncHistoryEntry(
                    task_name="directory_download",
                    content_id=meta.content_id,
                    site=meta.site,
                    author=meta.author,
                    desc=meta.desc,
                    output_path=str(item.artifact.output_path) if item.artifact else "",
                    status="ok",
                ),
            )
        payload.append(
            WorkflowResult(
                ok=item.ok,
                action=("reused" if reused else "downloaded") if item.ok else "failed",
                path=str(item.artifact.output_path) if item.artifact else "",
                content_id=meta.content_id if meta else "",
                title=(meta.title or meta.desc) if meta else "",
                error=item.error,
            ).to_dict()
        )
    return payload


def parse_profile_from_app_config(app_config_path: Path, profile_url: str) -> dict[str, Any]:
    app_config = ensure_app_config(app_config_path)
    base_dir = app_config_path.parent
    download_raw = app_config.get("download") or {}
    url = str(profile_url or "").strip()
    if not url:
        return ProfileParseResult(ok=False, url="", error="请先填写主页 URL").to_dict()
    ytdlp_extractor_args = _default_ytdlp_extractor_args(str(download_raw.get("ytdlp_extractor_args") or ""))
    ytdlp_cookies_file = _write_youtube_cookie_text(str(download_raw.get("youtube_cookies_text") or ""))
    if ytdlp_cookies_file is None:
        ytdlp_cookies_file = _resolve_optional_path(download_raw.get("youtube_cookies_path"), base_dir)
    ytdlp_remote_components = _as_bool(download_raw.get("ytdlp_remote_components"), True)
    try:
        result = expand_ytdlp_playlist(
            url,
            max_videos=1,
            cookies_file=ytdlp_cookies_file,
            order="latest",
            extractor_args=ytdlp_extractor_args,
            remote_components=ytdlp_remote_components,
        )
    except Exception as exc:
        if "space.bilibili.com" not in urlparse(url).netloc.lower():
            return ProfileParseResult(ok=False, url=url, error=str(exc)).to_dict()
        app_cfg = _workflow_app_config(base_dir, resolve_config_path(download_raw.get("output_dir", "./downloads"), base_dir))
        browser_path = app_cfg.browser_path or detect_system_browser_executable()
        if not browser_path:
            return ProfileParseResult(ok=False, url=url, error=f"{exc}；浏览器回退不可用：未找到 Google Chrome").to_dict()
        try:
            with open_download_browser_session(
                BrowserConfig(profile_dir=app_cfg.profile_dir, browser_path=browser_path, headless=app_cfg.headless)
            ) as browser:
                page = browser.new_page()
                try:
                    native_result = expand_profile(page=page, profile_url=url, max_videos=1, timeout_secs=app_cfg.timeout_secs)
                finally:
                    page.close()
            result = YtdlpPlaylistResult(video_urls=native_result.video_urls, uploader=native_result.author)
        except Exception as fallback_exc:
            return ProfileParseResult(ok=False, url=url, error=f"{exc}；浏览器回退失败：{fallback_exc}").to_dict()
    path_parts = [part for part in urlparse(url).path.split("/") if part]
    fallback_name = path_parts[-1] if path_parts else url
    if fallback_name.lower() in {"shorts", "videos", "streams", "reels"} and len(path_parts) > 1:
        fallback_name = path_parts[-2]
    if "space.bilibili.com" in urlparse(url).netloc.lower():
        uid = path_parts[0] if path_parts else ""
        fallback_name = f"B站 UP主 {uid}".strip()
    name = result.uploader or unquote(fallback_name) or url
    return ProfileParseResult(
        ok=True,
        url=url,
        name=name,
        first_video_url=result.video_urls[0] if result.video_urls else "",
    ).to_dict()


def _sidecar_for_video(video_path: Path) -> dict[str, Any]:
    sidecar = video_path.with_suffix(".json")
    if not sidecar.is_file():
        return {}
    try:
        data = json.loads(sidecar.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    return data if isinstance(data, dict) else {}


def _clean_title(title: str, strip_tags_mentions: bool) -> str:
    cleaned = str(title or "").strip()
    if strip_tags_mentions:
        cleaned = TAG_OR_MENTION_RE.sub("", cleaned)
    cleaned = " ".join(cleaned.split())
    return cleaned


def _format_template(template: str, values: dict[str, str]) -> str:
    class SafeMap(dict):
        def __missing__(self, key: str) -> str:
            return "{" + key + "}"

    return str(template or "{title}").format_map(SafeMap(values))


def run_publish_from_app_config(app_config_path: Path) -> list[dict[str, Any]]:
    app_config = ensure_app_config(app_config_path)
    base_dir = app_config_path.parent
    publish_raw = app_config.get("publish") or {}
    input_dir = resolve_config_path(
        publish_raw.get("input_dir") or (app_config.get("download") or {}).get("output_dir", "./downloads"),
        base_dir,
    )
    history_file = resolve_config_path(publish_raw.get("history_file", "./publish_history_mac.json"), base_dir)
    skill_dir = resolve_config_path(publish_raw.get("skill_dir", "~/.openclaw/workspace/skills/tencent-channel-community"), base_dir)
    guild_id = str(publish_raw.get("guild_id", "") or "").strip()
    channel_id = str(publish_raw.get("channel_id", "") or "").strip()
    scope = str(publish_raw.get("scope", "author_global") or "author_global")
    if scope == "channel":
        if not guild_id or not channel_id:
            return [WorkflowResult(ok=False, action="failed", error="频道内发帖需要填写频道ID和版块ID").to_dict()]
    else:
        guild_id = ""
        channel_id = ""
    feed_type = int(publish_raw.get("feed_type") or 1)
    limit = max(1, int(publish_raw.get("limit") or 1))
    strip_tags_mentions = _as_bool(publish_raw.get("strip_tags_mentions"), True)
    delete_after_publish = _as_bool(publish_raw.get("delete_after_publish"), True)
    retry_count = max(0, min(5, int(publish_raw.get("retry_count") or 2)))
    title_template = str(publish_raw.get("title_template") or "{title}")
    content_template = str(publish_raw.get("content_template") or "{title}")
    retry_video_path = str(publish_raw.get("retry_video_path") or "").strip()

    if not retry_video_path and not input_dir.exists():
        return [WorkflowResult(ok=False, action="failed", error=f"目录不存在: {input_dir}").to_dict()]
    if retry_video_path:
        retry_path = resolve_config_path(retry_video_path, base_dir)
        if not retry_path.is_file():
            return [WorkflowResult(ok=False, action="failed", path=str(retry_path), error=f"视频不存在: {retry_path}").to_dict()]
        videos = [retry_path]
    else:
        videos = sorted(
            [path for path in input_dir.rglob("*") if path.is_file() and path.suffix.lower() in VIDEO_SUFFIXES],
            key=lambda path: path.stat().st_mtime,
        )
    if not videos:
        return [WorkflowResult(ok=True, action="no_video").to_dict()]

    history = load_history(history_file)
    payload: list[dict[str, Any]] = []
    sent = 0
    for video_path in videos:
        sidecar = _sidecar_for_video(video_path)
        content_id = str(sidecar.get("content_id") or video_path.stem)
        task_name = "directory_publish"
        if not retry_video_path and find_processed_entry(history, task_name, content_id) is not None:
            action = "skipped"
            if delete_after_publish:
                video_path.unlink(missing_ok=True)
                video_path.with_suffix(".json").unlink(missing_ok=True)
                action = "skipped_deleted"
            payload.append(WorkflowResult(ok=True, action=action, path=str(video_path), content_id=content_id).to_dict())
            continue

        raw_title = str(sidecar.get("title") or sidecar.get("desc") or video_path.stem)
        clean_title = _clean_title(raw_title, strip_tags_mentions)
        values = {
            "title": clean_title,
            "raw_title": raw_title,
            "content_id": content_id,
            "author": str(sidecar.get("author", "")),
            "site": str(sidecar.get("site", "")),
            "desc": str(sidecar.get("desc", "")),
        }
        title = _format_template(title_template, values)
        content = _format_template(content_template, values)
        result = None
        for attempt in range(retry_count + 1):
            try:
                result = publish_to_channel(
                    skill_dir=skill_dir,
                    video_path=video_path,
                    guild_id=guild_id,
                    channel_id=channel_id,
                    title=title,
                    content=content,
                    feed_type=feed_type,
                )
            except Exception as exc:
                result = PublishResult(success=False, error=str(exc))
            if result.success:
                break
            if attempt < retry_count:
                log_warn(
                    "publish.retry",
                    content_id=content_id,
                    attempt=attempt + 1,
                    max_attempts=retry_count + 1,
                    error=result.error,
                )
                if is_login_state_publish_error(result.error):
                    status = check_tencent_login_status()
                    if not status.success:
                        log_warn("publish.login_status_check_failed", content_id=content_id, error=status.error)
                time.sleep(min(2 ** attempt, 8))
        if result.success and not str(result.share_url or "").strip():
            result = PublishResult(
                success=False,
                feed_id=result.feed_id,
                share_url=result.share_url,
                error="发布后未返回分享链接，已按失败处理，请稍后重新发布。",
            )
        if not result.success:
            add_entry(
                history,
                SyncHistoryEntry(
                    task_name=task_name,
                    content_id=content_id,
                    site=str(sidecar.get("site", "")),
                    author=str(sidecar.get("author", "")),
                    desc=str(sidecar.get("desc", "")) or title,
                    output_path=str(video_path),
                    status="failed",
                    error=result.error,
                ),
            )
            payload.append(
                WorkflowResult(ok=False, action="failed", path=str(video_path), content_id=content_id, title=title, error=result.error).to_dict()
            )
            continue
        add_entry(
            history,
            SyncHistoryEntry(
                task_name=task_name,
                content_id=content_id,
                site=str(sidecar.get("site", "")),
                author=str(sidecar.get("author", "")),
                desc=str(sidecar.get("desc", "")),
                output_path=str(video_path),
                feed_id=result.feed_id,
                share_url=result.share_url,
                status="ok",
            ),
        )
        if delete_after_publish:
            video_path.unlink(missing_ok=True)
            video_path.with_suffix(".json").unlink(missing_ok=True)
        payload.append(
            WorkflowResult(
                ok=True,
                action="published",
                path=str(video_path),
                content_id=content_id,
                title=title,
                feed_id=result.feed_id,
                share_url=result.share_url,
            ).to_dict()
        )
        sent += 1
        if sent >= limit:
            break
    return payload
