from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
import time
import fcntl
import http.cookiejar
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse
from urllib.request import HTTPCookieProcessor, Request, build_opener

from videocp.errors import DownloadError
from videocp.runtime_log import full_url, log_info, log_warn

NETSCAPE_COOKIE_HEADER = "# Netscape HTTP Cookie File\n# This file is generated by videocp\n\n"
YTDLP_FORMAT_SORT = "res,fps,vcodec:h264,acodec:m4a"
YTDLP_DOWNLOAD_FORMAT = "bv+ba/b"
YOUTUBE_COMPATIBLE_DOWNLOAD_FORMAT = (
    "bv*[vcodec^=avc1][ext=mp4]+ba[ext=m4a]/"
    "bv*[vcodec^=avc1]+ba/"
    "b[ext=mp4]/b"
)
YTDLP_REMOTE_COMPONENTS = "ejs:github"
QUALITY_HEIGHTS = {"2160": 2160, "1080": 1080, "720": 720, "480": 480}
YOUTUBE_LOCK_TIMEOUT_SECS = 900.0

_PLAYLIST_PATTERNS = (
    # YouTube
    re.compile(r"youtube\.com/@[^/]+(/(?:shorts|videos|streams))?/?$", re.IGNORECASE),
    re.compile(r"youtube\.com/channel/[^/]+", re.IGNORECASE),
    re.compile(r"youtube\.com/playlist\?", re.IGNORECASE),
    re.compile(r"youtube\.com/c/[^/]+", re.IGNORECASE),
    re.compile(r"youtube\.com/user/[^/]+", re.IGNORECASE),
    # Bilibili space video tab
    re.compile(r"space\.bilibili\.com/\d+(?:/video)?/?(?:\?.*)?$", re.IGNORECASE),
    # Instagram profile / reels tab (not single post/reel)
    re.compile(r"instagram\.com/(?!p/|reel/|stories/|explore/|accounts/|direct/)[^/?#]+(/reels)?/?$", re.IGNORECASE),
)


@dataclass(slots=True)
class YtdlpMetadata:
    id: str
    title: str
    uploader: str
    site: str
    url: str
    duration_secs: float = 0.0
    formats_count: int = 0
    max_resolution: int = 0


def write_netscape_cookies(cookies: list[dict[str, Any]], path: Path) -> None:
    """Write Playwright cookies to a Netscape cookie file for yt-dlp --cookies."""
    lines = [NETSCAPE_COOKIE_HEADER]
    for cookie in cookies:
        name = cookie.get("name", "")
        value = cookie.get("value", "")
        domain = cookie.get("domain", "")
        cookie_path = cookie.get("path", "/")
        secure = "TRUE" if cookie.get("secure", False) else "FALSE"
        expires = str(max(0, int(cookie.get("expires", 0))))
        domain_flag = "TRUE" if domain.startswith(".") else "FALSE"
        lines.append(f"{domain}\t{domain_flag}\t{cookie_path}\t{secure}\t{expires}\t{name}\t{value}\n")
    path.write_text("".join(lines), encoding="utf-8")


def is_ytdlp_playlist_url(url: str) -> bool:
    """Check if a URL looks like a playlist/profile page handled by yt-dlp."""
    return any(pattern.search(url) for pattern in _PLAYLIST_PATTERNS)


def _safe_float(value: object) -> float:
    try:
        return float(value or 0)
    except (TypeError, ValueError):
        return 0.0


def _yt_dlp_cmd() -> list[str]:
    return [sys.executable, "-m", "yt_dlp"]


def _is_youtube_url(url: str) -> bool:
    normalized = str(url or "").lower()
    return "youtube.com" in normalized or "youtu.be" in normalized


def _is_bilibili_space_url(url: str) -> bool:
    return "space.bilibili.com" in str(url or "").lower()


@contextmanager
def _youtube_process_lock(url: str):
    if not _is_youtube_url(url):
        yield
        return
    lock_path = Path(tempfile.gettempdir()) / "videocp-youtube-ytdlp.lock"
    with lock_path.open("a", encoding="utf-8") as lock_file:
        deadline = time.monotonic() + float(os.environ.get("VIDEOCP_YOUTUBE_LOCK_TIMEOUT_SECS", YOUTUBE_LOCK_TIMEOUT_SECS))
        acquired = False
        while not acquired:
            try:
                fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
                acquired = True
            except BlockingIOError:
                if time.monotonic() >= deadline:
                    log_warn("youtube.lock.timeout", lock_path=str(lock_path))
                    raise DownloadError(
                        "YouTube 下载队列等待超时：当前有太多 YouTube 下载任务正在运行，"
                        "请停止部分任务或稍后重试。"
                    )
                time.sleep(0.25)
        try:
            yield
        finally:
            if acquired:
                fcntl.flock(lock_file.fileno(), fcntl.LOCK_UN)


def _with_bilibili_space_order(url: str, order: str) -> str:
    parsed = urlparse(url)
    if "space.bilibili.com" not in parsed.netloc.lower():
        return url
    query = dict(parse_qsl(parsed.query, keep_blank_values=True))
    query["order"] = "click" if order == "popular" else "pubdate"
    return urlunparse(parsed._replace(query=urlencode(query)))


@dataclass(slots=True)
class YtdlpPlaylistResult:
    video_urls: list[str]
    uploader: str


def _walk_json(value: Any):
    if isinstance(value, dict):
        yield value
        for child in value.values():
            yield from _walk_json(child)
    elif isinstance(value, list):
        for child in value:
            yield from _walk_json(child)


def _youtube_initial_data(html: str) -> dict[str, Any]:
    marker_match = re.search(r"(?:var ytInitialData = |window\[\"ytInitialData\"\] = )", html)
    if not marker_match:
        raise DownloadError("YouTube channel page did not contain initial data")
    try:
        data, _ = json.JSONDecoder().raw_decode(html[marker_match.end():])
    except json.JSONDecodeError as exc:
        raise DownloadError("YouTube channel page returned invalid initial data") from exc
    return data


def _youtube_continuation_token(data: dict[str, Any], *, popular_chip: bool) -> str:
    for item in _walk_json(data):
        if popular_chip:
            chip = item.get("chipViewModel")
            if not isinstance(chip, dict):
                continue
            labels = {
                str(chip.get("text", "")).strip().lower(),
                str(chip.get("accessibilityLabel", "")).strip().lower(),
            }
            if not labels.intersection({"popular", "热门", "最热门", "熱門", "最熱門"}):
                continue
            command = chip.get("tapCommand", {}).get("innertubeCommand", {})
        else:
            continuation = item.get("continuationItemRenderer")
            if not isinstance(continuation, dict):
                continue
            command = continuation.get("continuationEndpoint", {})
        token = command.get("continuationCommand", {}).get("token", "")
        if token:
            return str(token)
    return ""


def _youtube_video_entries(data: dict[str, Any]) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    seen: set[str] = set()
    for item in _walk_json(data):
        renderer = item.get("videoRenderer") or item.get("gridVideoRenderer")
        if not isinstance(renderer, dict):
            lockup = item.get("lockupViewModel")
            if not isinstance(lockup, dict) or lockup.get("contentType") != "LOCKUP_CONTENT_TYPE_VIDEO":
                continue
            video_id = str(lockup.get("contentId", ""))
            title = str(lockup.get("metadata", {}).get("lockupMetadataViewModel", {}).get("title", {}).get("content", ""))
        else:
            video_id = str(renderer.get("videoId", ""))
            title = "".join(str(run.get("text", "")) for run in renderer.get("title", {}).get("runs", []))
        if video_id and video_id not in seen:
            seen.add(video_id)
            entries.append({"id": video_id, "title": title})
    return entries


def _expand_youtube_popular_playlist(
    url: str,
    max_videos: int,
    cookies_file: Path | None,
) -> YtdlpPlaylistResult:
    cookie_jar = http.cookiejar.MozillaCookieJar()
    if cookies_file is not None and cookies_file.exists():
        try:
            cookie_jar.load(str(cookies_file), ignore_discard=True, ignore_expires=True)
        except (OSError, http.cookiejar.LoadError):
            pass
    opener = build_opener(HTTPCookieProcessor(cookie_jar))
    headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
        "Accept-Language": "en-US,en;q=0.9,zh-CN;q=0.8",
    }
    try:
        with opener.open(Request(url, headers=headers), timeout=30) as response:
            html = response.read().decode("utf-8", errors="replace")
    except OSError as exc:
        raise DownloadError(f"YouTube popular page request failed: {exc}") from exc

    initial_data = _youtube_initial_data(html)
    token = _youtube_continuation_token(initial_data, popular_chip=True)
    if not token:
        raise DownloadError("YouTube channel page did not expose the Popular filter")
    api_key_match = re.search(r'"INNERTUBE_API_KEY":"([^"]+)', html)
    client_version_match = re.search(r'"INNERTUBE_CLIENT_VERSION":"([^"]+)', html)
    if not api_key_match or not client_version_match:
        raise DownloadError("YouTube channel page did not expose API configuration")

    api_url = f"https://www.youtube.com/youtubei/v1/browse?key={api_key_match.group(1)}&prettyPrint=false"
    entries: list[dict[str, Any]] = []
    seen_tokens: set[str] = set()
    while token and token not in seen_tokens and len(entries) < max_videos:
        seen_tokens.add(token)
        payload = json.dumps({
            "context": {
                "client": {
                    "clientName": "WEB",
                    "clientVersion": client_version_match.group(1),
                },
            },
            "continuation": token,
        }).encode("utf-8")
        request = Request(
            api_url,
            data=payload,
            headers={**headers, "Content-Type": "application/json", "Origin": "https://www.youtube.com"},
        )
        try:
            with opener.open(request, timeout=30) as response:
                page_data = json.load(response)
        except (OSError, json.JSONDecodeError) as exc:
            raise DownloadError(f"YouTube popular list request failed: {exc}") from exc
        entries.extend(_youtube_video_entries(page_data))
        token = _youtube_continuation_token(page_data, popular_chip=False)

    video_urls = [
        f"https://www.youtube.com/watch?v={entry['id']}"
        for entry in entries[:max_videos]
    ]
    if not video_urls:
        raise DownloadError("YouTube Popular filter returned no videos")
    uploader = ""
    for item in _walk_json(initial_data):
        metadata = item.get("channelMetadataRenderer")
        if isinstance(metadata, dict) and metadata.get("title"):
            uploader = str(metadata["title"])
            break
    log_info("ytdlp.playlist.youtube_popular_complete", url=full_url(url), videos=len(video_urls))
    return YtdlpPlaylistResult(video_urls=video_urls, uploader=uploader)


def _entry_url(entry: dict[str, Any]) -> str:
    entry_url = str(entry.get("url", "") or "")
    if entry_url:
        return entry_url
    if entry.get("id") and str(entry.get("ie_key", "")).lower() == "bilibili":
        return f"https://www.bilibili.com/video/{entry['id']}"
    if entry.get("id"):
        return f"https://www.youtube.com/watch?v={entry['id']}"
    return ""


def expand_ytdlp_playlist(
    url: str,
    max_videos: int,
    cookies_file: Path | None = None,
    order: str = "latest",
    extractor_args: str = "",
    remote_components: bool = False,
) -> YtdlpPlaylistResult:
    """Expand a playlist/channel URL to individual video URLs via yt-dlp."""
    normalized_order = "popular" if str(order).lower() == "popular" else "latest"
    log_info("ytdlp.playlist.start", url=full_url(url), max_videos=max_videos, order=normalized_order)
    if normalized_order == "popular" and _is_youtube_url(url):
        try:
            return _expand_youtube_popular_playlist(url, max_videos, cookies_file)
        except DownloadError as exc:
            log_warn(
                "ytdlp.playlist.youtube_popular_fallback",
                url=full_url(url),
                error=str(exc),
                message="YouTube 热门筛选暂时不可用，将扩大候选范围后按播放量降级排序",
            )
    playlist_url = _with_bilibili_space_order(url, normalized_order)
    is_bilibili_space = _is_bilibili_space_url(playlist_url)
    fetch_count = (
        max_videos
        if normalized_order == "latest" or is_bilibili_space
        else max(max_videos * 4, max_videos)
    )
    ranges = [(1, fetch_count)]
    if is_bilibili_space and fetch_count > 25:
        # Some Bilibili space responses stop after the first 25 entries even
        # when yt-dlp is asked for a larger continuous range. Separate range
        # requests force the extractor to fetch every required page.
        ranges = [
            (start, min(start + 24, fetch_count))
            for start in range(1, fetch_count + 1, 25)
        ]

    entries: list[dict[str, Any]] = []
    seen_entry_urls: set[str] = set()
    uploader = ""

    for range_start, range_end in ranges:
        result = None
        max_attempts = 3 if is_bilibili_space else 1
        for attempt in range(max_attempts):
            cmd = [
                *_yt_dlp_cmd(),
                "--ignore-config",
                "--flat-playlist",
                "--dump-json",
                "--no-warnings",
                "--playlist-items", f"{range_start}:{range_end}",
            ]
            if cookies_file is not None:
                cmd.extend(["--cookies", str(cookies_file)])
            if remote_components:
                cmd.extend(["--remote-components", YTDLP_REMOTE_COMPONENTS])
            _append_youtube_extractor_args(cmd, extractor_args)
            cmd.append(playlist_url)
            try:
                result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
            except FileNotFoundError:
                raise DownloadError("yt-dlp not found. Install it: pip install yt-dlp or brew install yt-dlp")
            except subprocess.TimeoutExpired:
                raise DownloadError("yt-dlp playlist expansion timed out after 120 seconds")
            error_text = (result.stderr or "").lower()
            blocked = result.returncode != 0 and any(
                marker in error_text for marker in ("server (352)", "server (412)", "blocked by server", "rejected by server")
            )
            if not blocked or attempt >= max_attempts - 1:
                break
            wait_secs = 5 * (attempt + 1)
            log_warn(
                "ytdlp.playlist.bilibili_retry",
                range=f"{range_start}:{range_end}",
                attempt=attempt + 1,
                wait_secs=wait_secs,
                error=(result.stderr or "").strip(),
            )
            time.sleep(wait_secs)
        assert result is not None
        if result.returncode != 0:
            stderr = result.stderr.strip()
            if is_bilibili_space and entries:
                log_warn(
                    "ytdlp.playlist.range_failed",
                    url=full_url(playlist_url),
                    range=f"{range_start}:{range_end}",
                    videos=len(entries),
                    error=stderr or "unknown error",
                )
                break
            raise DownloadError(f"yt-dlp playlist expansion failed: {stderr or 'unknown error'}")

        range_entries = 0
        for line in result.stdout.strip().splitlines():
            if not line.strip():
                continue
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                continue
            entry_url = _entry_url(entry)
            if not entry_url or entry_url in seen_entry_urls:
                continue
            seen_entry_urls.add(entry_url)
            entries.append(entry)
            range_entries += 1
            if not uploader:
                uploader = str(entry.get("uploader", entry.get("channel", "")))
        log_info(
            "ytdlp.playlist.range_complete",
            url=full_url(playlist_url),
            range=f"{range_start}:{range_end}",
            videos=range_entries,
            total=len(entries),
        )
        if is_bilibili_space and range_entries == 0:
            break

    if normalized_order == "popular":
        entries.sort(key=lambda item: int(item.get("view_count") or 0), reverse=True)
    video_urls = [entry_url for entry in entries if (entry_url := _entry_url(entry))][:max_videos]

    log_info("ytdlp.playlist.complete", url=full_url(url), videos=len(video_urls), uploader=uploader)
    return YtdlpPlaylistResult(video_urls=video_urls, uploader=uploader)


def _append_youtube_extractor_args(cmd: list[str], extractor_args: str = "") -> None:
    value = extractor_args.strip()
    if value:
        cmd.extend(["--extractor-args", value])
    bundled_server = os.environ.get("VIDEOCP_BUNDLED_BGUTIL_SERVER", "").strip()
    if bundled_server:
        cmd.extend(["--extractor-args", f"youtubepot-bgutilscript:server_home={bundled_server}"])


def fetch_ytdlp_metadata(
    url: str,
    cookies_file: Path | None = None,
    extractor_args: str = "",
    remote_components: bool = False,
) -> YtdlpMetadata:
    """Fetch video metadata via yt-dlp --dump-json without downloading."""
    cmd = [
        *_yt_dlp_cmd(),
        "--ignore-config",
        "--dump-json",
        "--no-download",
        "--no-warnings",
        "--ignore-no-formats-error",
    ]
    if cookies_file is not None:
        cmd.extend(["--cookies", str(cookies_file)])
    if remote_components:
        cmd.extend(["--remote-components", YTDLP_REMOTE_COMPONENTS])
    _append_youtube_extractor_args(cmd, extractor_args)
    cmd.append(url)
    log_info("ytdlp.metadata.start", url=full_url(url))
    try:
        with _youtube_process_lock(url):
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    except FileNotFoundError:
        raise DownloadError("yt-dlp not found. Install it: pip install yt-dlp or brew install yt-dlp")
    except subprocess.TimeoutExpired:
        raise DownloadError("yt-dlp metadata fetch timed out after 60 seconds")
    if result.returncode != 0:
        stderr = result.stderr.strip()
        raise DownloadError(f"yt-dlp metadata failed: {stderr or 'unknown error'}")
    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise DownloadError(f"yt-dlp returned invalid JSON: {exc}")
    formats = data.get("formats")
    video_resolutions = [
        min(int(item.get("width") or 0), int(item.get("height") or 0))
        for item in formats or []
        if isinstance(item, dict)
        and str(item.get("vcodec") or "none") != "none"
        and int(item.get("width") or 0) > 0
        and int(item.get("height") or 0) > 0
    ]
    meta = YtdlpMetadata(
        id=str(data.get("id", "")),
        title=str(data.get("title", "")),
        uploader=str(data.get("uploader", data.get("channel", data.get("uploader_id", "")))),
        site=str(data.get("extractor_key", data.get("extractor", ""))).lower(),
        url=url,
        duration_secs=_safe_float(data.get("duration")),
        formats_count=len(formats) if isinstance(formats, list) else 0,
        max_resolution=max(video_resolutions, default=0),
    )
    log_info(
        "ytdlp.metadata.complete",
        id=meta.id,
        title=meta.title,
        uploader=meta.uploader,
        site=meta.site,
        duration_secs=f"{meta.duration_secs:.1f}" if meta.duration_secs else None,
        formats=meta.formats_count,
        max_resolution=meta.max_resolution,
    )
    return meta


def download_with_ytdlp(
    url: str,
    output_path: Path,
    cookies_file: Path | None = None,
    timeout_secs: int = 300,
    extractor_args: str = "",
    remote_components: bool = False,
    quality: str = "best",
) -> None:
    """Download video using yt-dlp subprocess."""
    temp_template = str(output_path.with_suffix(".%(ext)s"))
    normalized_quality = str(quality or "best").strip().lower()
    max_height = QUALITY_HEIGHTS.get(normalized_quality)
    format_selector = YOUTUBE_COMPATIBLE_DOWNLOAD_FORMAT if _is_youtube_url(url) else YTDLP_DOWNLOAD_FORMAT
    format_sort = YTDLP_FORMAT_SORT
    if max_height:
        # yt-dlp's "res" uses the smaller video dimension. This keeps portrait
        # 1080x1920 video in the 1080p tier instead of filtering it out by height.
        format_selector = YOUTUBE_COMPATIBLE_DOWNLOAD_FORMAT if _is_youtube_url(url) else "bv+ba/b"
        format_sort = f"res:{max_height},fps,vcodec:h264,acodec:m4a"
    cmd = [
        *_yt_dlp_cmd(),
        "--ignore-config",
        "--no-warnings",
        "--no-playlist",
        "-f", format_selector,
        "-S", format_sort,
        "-o", temp_template,
        "--merge-output-format", "mp4",
    ]
    if cookies_file is not None:
        cmd.extend(["--cookies", str(cookies_file)])
    if remote_components:
        cmd.extend(["--remote-components", YTDLP_REMOTE_COMPONENTS])
    _append_youtube_extractor_args(cmd, extractor_args)
    cmd.append(url)
    log_info(
        "ytdlp.download.start",
        url=full_url(url),
        output=str(output_path),
        timeout_secs=timeout_secs,
        quality=normalized_quality,
    )
    try:
        with _youtube_process_lock(url):
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout_secs)
    except FileNotFoundError:
        raise DownloadError("yt-dlp not found. Install it: pip install yt-dlp or brew install yt-dlp")
    except subprocess.TimeoutExpired:
        raise DownloadError(f"yt-dlp download timed out after {timeout_secs} seconds")
    if result.returncode != 0:
        stderr = result.stderr.strip()
        raise DownloadError(f"yt-dlp download failed: {stderr or 'unknown error'}")
    # yt-dlp may produce a file with a different extension; find the actual output
    if not output_path.exists():
        # look for the file yt-dlp actually created (e.g. .webm, .mkv merged to .mp4)
        parent = output_path.parent
        stem = output_path.stem
        candidates = sorted(parent.glob(f"{stem}.*"), key=lambda p: p.stat().st_mtime, reverse=True)
        actual = next((c for c in candidates if c.suffix != ".json" and c.suffix != ".part"), None)
        if actual is not None and actual != output_path:
            actual.rename(output_path)
        elif not output_path.exists():
            raise DownloadError(f"yt-dlp completed but output file not found: {output_path}")
    log_info("ytdlp.download.complete", output=str(output_path), bytes=output_path.stat().st_size)
